try {
    Number(5).toPrecision(300)
    } catch(e) {
    console.log("There was an error")
    }